/**
 * (c) 2018 Libelf.JS
 * Wrapper made by Alexandro Sanchez Bach.
 */

/* ELF constants */

// e_type
const e_type_strings = {
    0:     "ET_NONE",
    1:     "ET_REL",
    2:     "ET_EXEC",
    3:     "ET_DYN",
    4:     "ET_CORE",
    5:     "ET_NUM",
};

// e_machine
const e_machine_strings = {
    0:     "EM_NONE",
    1:     "EM_M32",
    2:     "EM_SPARC",
    3:     "EM_386",
    4:     "EM_68K",
    5:     "EM_88K",
    6:     "EM_486",
    7:     "EM_860",
    8:     "EM_MIPS",
    9:     "EM_S370",
    10:    "EM_MIPS_RS3_LE",
    11:    "EM_SPARC64",
    15:    "EM_PARISC",
    17:    "EM_VPP500",
    18:    "EM_SPARC32PLUS",
    19:    "EM_960",
    20:    "EM_PPC",
    21:    "EM_PPC64",
    22:    "EM_S390",
    36:    "EM_V800",
    37:    "EM_FR20",
    38:    "EM_RH32",
    39:    "EM_RCE",
    40:    "EM_ARM",
    41:    "EM_ALPHA",
    42:    "EM_SH",
    43:    "EM_SPARCV9",
    44:    "EM_TRICORE",
    45:    "EM_ARC",
    46:    "EM_H8_300",
    47:    "EM_H8_300H",
    48:    "EM_H8S",
    49:    "EM_H8_500",
    50:    "EM_IA_64",
    51:    "EM_MIPS_X",
    52:    "EM_COLDFIRE",
    53:    "EM_68HC12",
    54:    "EM_MMA",
    55:    "EM_PCP",
    56:    "EM_NCPU",
    57:    "EM_NDR1",
    58:    "EM_STARCORE",
    59:    "EM_ME16",
    60:    "EM_ST100",
    61:    "EM_TINYJ",
    62:    "EM_X86_64",
    63:    "EM_PDSP",
    66:    "EM_FX66",
    67:    "EM_ST9PLUS",
    68:    "EM_ST7",
    69:    "EM_68HC16",
    70:    "EM_68HC11",
    71:    "EM_68HC08",
    72:    "EM_68HC05",
    73:    "EM_SVX",
    74:    "EM_ST19",
    75:    "EM_VAX",
    76:    "EM_CRIS",
    77:    "EM_JAVELIN",
    78:    "EM_FIREPATH",
    79:    "EM_ZSP",
    80:    "EM_MMIX",
    81:    "EM_HUANY",
    82:    "EM_PRISM",
    83:    "EM_AVR",
    84:    "EM_FR30",
    85:    "EM_D10V",
    86:    "EM_D30V",
    87:    "EM_V850",
    88:    "EM_M32R",
    89:    "EM_MN10300",
    90:    "EM_MN10200",
    91:    "EM_PJ",
    92:    "EM_OPENRISC",
    93:    "EM_ARC_A5",
    94:    "EM_XTENSA",
    95:    "EM_VIDEOCORE",
    96:    "EM_TMM_GPP",
    97:    "EM_NS32K",
    98:    "EM_TPC",
    99:    "EM_SNP1K",
    100:   "EM_ST200",
    101:   "EM_IP2K",
    102:   "EM_MAX",
    103:   "EM_CR",
    104:   "EM_F2MC16",
    105:   "EM_MSP430",
    106:   "EM_BLACKFIN",
    107:   "EM_SE_C33",
    108:   "EM_SEP",
    109:   "EM_ARCA",
    110:   "EM_UNICORE",
};

// e_version
const e_version_strings = {
    0:     "EV_NONE",
    1:     "EV_CURRENT",
    2:     "EV_NUM",
};

// p_type
const p_type_strings = {
    0:     "PT_NULL",
    1:     "PT_LOAD",
    2:     "PT_DYNAMIC",
    3:     "PT_INTERP",
    4:     "PT_NOTE",
    5:     "PT_SHLIB",
    6:     "PT_PHDR",
    7:     "PT_TLS",
    8:     "PT_NUM",
};

// p_flags
const p_flags_strings = {
    0x1:   "PF_X",
    0x2:   "PF_W",
    0x4:   "PF_R",
};

// sh_type
const sh_type_strings = {
    0:     "SHT_NULL",
    1:     "SHT_PROGBITS",
    2:     "SHT_SYMTAB",
    3:     "SHT_STRTAB",
    4:     "SHT_RELA",
    5:     "SHT_HASH",
    6:     "SHT_DYNAMIC",
    7:     "SHT_NOTE",
    8:     "SHT_NOBITS",
    9:     "SHT_REL",
    10:    "SHT_SHLIB",
    11:    "SHT_DYNSYM",
    14:    "SHT_INIT_ARRAY",
    15:    "SHT_FINI_ARRAY",
    16:    "SHT_PREINIT_ARRAY",
    17:    "SHT_GROUP",
    18:    "SHT_SYMTAB_SHNDX",
    19:    "SHT_NUM",
};

// dt_type
const dt_type_strings = {
    0:     "DT_NULL",
    1:     "DT_NEEDED",
    2:     "DT_PLTRELSZ",
    3:     "DT_PLTGOT",
    4:     "DT_HASH",
    5:     "DT_STRTAB",
    6:     "DT_SYMTAB",
    7:     "DT_RELA",
    8:     "DT_RELASZ",
    9:     "DT_RELAENT",
    10:    "DT_STRSZ",
    11:    "DT_SYMENT",
    12:    "DT_INIT",
    13:    "DT_FINI",
    14:    "DT_SONAME",
    15:    "DT_RPATH",
    16:    "DT_SYMBOLIC",
    17:    "DT_REL",
    18:    "DT_RELSZ",
    19:    "DT_RELENT",
    20:    "DT_PLTREL",
    21:    "DT_DEBUG",
    22:    "DT_TEXTREL",
    23:    "DT_JMPREL",
    24:    "DT_BIND_NOW",
    25:    "DT_INIT_ARRAY",
    26:    "DT_FINI_ARRAY",
    27:    "DT_INIT_ARRAYSZ",
    28:    "DT_FINI_ARRAYSZ",
    29:    "DT_RUNPATH",
    30:    "DT_FLAGS",
    32:    "DT_ENCODING",
    32:    "DT_PREINIT_ARRAY",
    33:    "DT_PREINIT_ARRAYSZ",
    34:    "DT_NUM",
};

// dt_flags
const dt_flags_strings = {
    0x01:  "DF_ORIGIN",
    0x02:  "DF_SYMBOLIC",
    0x04:  "DF_TEXTREL",
    0x08:  "DF_BIND_NOW",
    0x10:  "DF_STATIC_TLS",
};
